### PR TITLE
feat: remove python dependency for a build script

### PR DESCRIPTION
**Pull request by seuros**
I will other PR  later.

part of #132

### CODE REVIEW

**Comment by bvernoux** [comment]
The drawback of replacing python script by bash script is it will be working only on Linux computer (or MSYS2/MINGW64) I will really prefer a more universal way to do it by replacing those python script by C portable code built as native executable which can be executed on any computer.
To be discussed with @Baldanos

**Comment by seuros** [comment]
The script should work with WSL 2 (i need to test it) and it does work in macos.
We can also add Powershell if needed if the aim is to remove Python.

For cross-portability, I can provide Go, not C.

**Comment by bvernoux** [comment]
> The script should work with WSL 2 (i need to test it) and it does work in macos. We can also add Powershell if needed if the aim is to remove Python.
> 
> For cross-portability, I can provide Go, not C.

I will prefer to avoid Go (which will add even more complexity/dependencies) the aim is to have something simple and multi platform at least to build the firmware.
At start we can live with bash/shell solution (it is always better than to have Python dependency for 2 scripts) to be discussed with @Baldanos

**Comment by Baldanos** [comment]
Nice idea, I had a quite similar approach in this branch here: https://github.com/Baldanos/hydrafw/tree/nopython

Replacing Python with Go or something else wouldn't make any improvement. However, as long as a fix is available and works on Windows and Linux, I think we should go for it

**Comment by bvernoux** [comment]
I prefer to avoid powershell specific windows stuff especially we can build it with MSYS2/MINGW64 like it is described in the https://github.com/hydrabus/hydrafw/wiki/how-to-build-flash-and-use-hydrafw-on-windows

**Comment by bvernoux** [comment]
Thanks for your contribution

**Pull request merged**
