### PR TITLE
Add read with timeout feature

### PR DESCRIPTION
**Pull request by Baldanos**
Based on #164 this PR adds a read with timeout feature.

1) Add a `timeout` keyword to set timeout in miliseconds on all relevant modes (UART, LIN, Smartcard)
2) Change `read` and `hd` commands behavior. They now display read bytes and show an message if not every byte requested could be read
3) Some cleanup of now unused functions

Example with UART in loopback mode:
```
> uart 
Device: UART1
Speed: 9600 bps
Parity: none
Stop bits: 1
Timeout: 10000 msec
uart1> timeout 1000
uart1> show 
Device: UART1
Speed: 9600 bps
Parity: none
Stop bits: 1
Timeout: 1000 msec
uart1> 0x41 r:8
WRITE: 0x41
! TIMEOUT: read 1 out of 8
READ: 0x41
uart1> 0x41 hd:8
WRITE: 0x41
41                                                |  A 
! TIMEOUT: read 1 out of 8
uart1>
```

This might need to be further tested before being included. Maybe @bvernoux and @0xDRRB could do some tests ?

### CODE REVIEW

**Comment by 0xDRRB** [comment]
I've just tested it with a smartcard and it works like a charm:

```
> smartcard 
Device: SMARTCARD1
Speed: 9408 bps
Parity: even
Stop bits: 1.5
Convention: normal
Prescaler: 12 / 3.50mhz
Timeout: 10000 msec

smartcard1> timeout 2000

smartcard1> ]%%[read:33 
RST DOWN
DELAY: 1 ms
DELAY: 1 ms
RST UP
! TIMEOUT: read 18 out of 33
READ: 0x3B 0xF8 0x13 0x00 0x00 0x81 0x31 0xFE 0x45 0x4A 0x43 0x4F 0x50 0x76 0x32 0x34 0x31 0xB7 
smartcard1> 0x00 0x00 0x0f 0x00 0xa4 0x04 0x00 0x0a 0xf2 0x76 0xa2 0x88 0xbc 0xde 0xad 0xbe 0xef 0x01 0x94 % read:18 
WRITE: 0x00 0x00 0x0F 0x00 0xA4 0x04 0x00 0x0A 0xF2 0x76 0xA2 0x88 0xBC 0xDE 0xAD 0xBE 0xEF 0x01 0x94 
DELAY: 1 ms
! TIMEOUT: read 6 out of 18
READ: 0x00 0x00 0x02 0x90 0x00 0x92 
```
The fact that using the `atr` command resets the timeout to the default value (10000ms) is annoying but, as @bvernoux pointed out in #164, 10000ms is huge and could be reduced to 1000 or 2000, which would mitigate the problem.

Having said that, the `atr` command isn't really useful now that a `]%%[read:33` does the job without a hitch.

(It would be great to be able to define aliases for certain recurring commands, like "`alias atr = ]%%[read:33`" or something like that. Maybe loaded from the MMC as a text file like `smartcard.aliases`, `uart.aliases`, `spi.aliases`)

I'll do some more tests over the weekend and let you know if I come across any problems.

**Comment by Baldanos** [comment]
Thank you both for testing ;)

We can totally lower the default timeout values.

Regarding the `atr` command, the fact that it parses and displays the timing information is a good reason to keep it. I'll push a fix in this PR so it reuses the current timeout.

**Comment by bvernoux** [comment]
Maybe add that feature on Wiegand also (I have tested uart with success)

**Comment by Baldanos** [comment]
> Maybe add that feature on Wiegand also (I have tested uart with success)

I did a quick check, and Wiegand could use a full rewrite. 
Unfortunately I do not have access to a Wiegand interface so I would not attempt such rewrite without tests.

**Comment by bvernoux** [comment]
> > Maybe add that feature on Wiegand also (I have tested uart with success)
> 
> I did a quick check, and Wiegand could use a full rewrite. Unfortunately I do not have access to a Wiegand interface so I would not attempt such rewrite without tests.

Wiegand is clearly not a priority, I have nothing to test it too (so far) so keep that for future potential improvement

**Pull request merged**
